import { test, expect } from '@playwright/test'

test('Upload, Freigabe, Veröffentlichung, SQL, Tutor und Rückblick',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'SQL verstehen. Selbstständig anwenden.'})).toBeVisible()
  await page.getByRole('button',{name:/Materialien & Aufgaben/}).click()
  await page.getByRole('button',{name:'Oracle-Schema laden'}).click()
  await page.getByRole('checkbox',{name:'LAB.EMPLOYEES'}).check()
  await page.getByRole('button',{name:'Freigabe speichern'}).click()
  await expect(page.getByText('Tabellenfreigabe gespeichert.')).toBeVisible()
  await page.getByLabel('Material hochladen').setInputFiles({name:'select.md',mimeType:'text/markdown',buffer:Buffer.from('# SELECT\nMit SELECT wählst du Spalten aus.')})
  await expect(page.getByText('Material hochgeladen.')).toBeVisible()
  await page.getByRole('checkbox',{name:'select.md'}).check()
  await page.getByLabel('Tabellen wählen (maximal zwei)').selectOption('LAB.EMPLOYEES')
  await page.getByRole('button',{name:'Zuordnung speichern'}).click()
  await expect(page.getByText('Materialien zugeordnet.')).toBeVisible()
  await page.getByRole('button',{name:'Neue Aufgabe'}).click()
  await page.getByLabel('Titel',{exact:true}).fill('Alle Namen lesen')
  await page.getByLabel('Aufgabenstellung').fill('Zeige alle Namen aus der Mitarbeitertabelle.')
  await page.getByLabel('Referenz-SQL (nur Vorbereitung)').fill('SELECT name FROM LAB.EMPLOYEES')
  await page.getByLabel('Hinweis 1',{exact:true}).fill('Wähle die Namensspalte.')
  await page.getByLabel('Hinweis 2',{exact:true}).fill('Beginne mit SELECT.')
  await page.getByLabel('Hinweis 3',{exact:true}).fill('Nutze name und LAB.EMPLOYEES.')
  await page.getByRole('button',{name:'Entwurf speichern'}).click()
  await expect(page.getByText('Entwurf gespeichert.')).toBeVisible()
  await page.getByRole('button',{name:'Veröffentlichen',exact:true}).click()
  await expect(page.getByText('Aufgabe veröffentlicht.')).toBeVisible()
  await page.getByRole('button',{name:/Themenübersicht/}).click()
  await page.getByRole('button',{name:'Lernen starten →'}).click()
  await expect(page.getByRole('heading',{name:'Alle Namen lesen'})).toBeVisible()
  await page.locator('.cm-content').click()
  await page.keyboard.press('ControlOrMeta+A')
  await page.keyboard.insertText('SELECT name FROM LAB.EMPLOYEES')
  await page.getByRole('button',{name:'Abfrage ausführen'}).click()
  await expect(page.getByText('Richtig gelöst.')).toBeVisible()
  await expect(page.getByRole('cell',{name:'Ada',exact:true})).toBeVisible()
  await page.getByLabel('Deine Verständnisfrage').fill('Was macht SELECT?')
  await page.getByRole('button',{name:'Frage senden'}).click()
  await expect(page.getByText('Fester Tutorhinweis · Modell nicht verfügbar')).toBeVisible()
  await page.getByRole('button',{name:'Hinweis 1 von 3 anfordern'}).click()
  await expect(page.getByText('Wähle die Namensspalte.')).toBeVisible()
  await page.getByRole('button',{name:/Rückblick/}).click()
  await expect(page.locator('summary').filter({hasText:'Korrekt'})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:/Lernarbeitsplatz/}).click()
  await expect(page.getByRole('heading',{name:'Alle Namen lesen'})).toBeVisible()
  await expect(page.locator('.cm-content')).toContainText('SELECT name FROM LAB.EMPLOYEES')
  await expect(page.getByText('Wähle die Namensspalte.')).toBeVisible()
  await page.context().setOffline(true)
  await expect(page.getByText(/Es werden keine Versuche automatisch nachgesendet/)).toBeVisible()
  await expect(page.getByRole('button',{name:'Abfrage ausführen'})).toBeDisabled()
  await expect(page.locator('.cm-content')).toContainText('SELECT name FROM LAB.EMPLOYEES')
  await page.context().setOffline(false)
  expect(errors).toEqual([])
  await page.screenshot({path:'test-results/learning-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'Abfrage ausführen'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:'test-results/learning-mobile.png',fullPage:true})
})
